# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=10)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('detail', models.TextField()),
                ('procedure', models.TextField()),
                ('enrollUrl', models.URLField()),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
