# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 04:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=10)),
                ('group_size', models.IntegerField(default=1)),
                ('enroll_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('enroll_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(default='')),
                ('img_url', models.URLField(default='')),
                ('enroll_url', models.URLField(default='')),
                ('charge', models.IntegerField(default=0)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('current_stage', models.IntegerField(default=0)),
                ('judges', models.ManyToManyField(related_name='judged_competitions', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('criterion', models.TextField(default='')),
                ('stage', models.IntegerField()),
                ('is_assigned', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_list', to='basic.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('rank', models.TextField()),
                ('current_stage', models.IntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_groups', to='basic.Competition')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='joint_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('has_commit', models.BooleanField(default=False)),
                ('commit_path', models.FilePathField(blank=True)),
                ('submission', models.CharField(default='', max_length=50)),
                ('score', models.FloatField(default=0.0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_list', to='basic.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_notices', to='basic.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_list', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_meta_list', to='basic.GStage')),
            ],
        ),
    ]
