# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmeta',
            old_name='marked',
            new_name='reviewed',
        ),
        migrations.AddField(
            model_name='cstage',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
