# Generated by Django 2.1.2 on 2018-10-29 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantGroupConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContestantUser',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=512)),
                ('email_address', models.EmailField(max_length=254)),
                ('introduction', models.TextField()),
                ('source_school', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('commit_filepath', models.FilePathField()),
                ('rank', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JudgeCompetitionConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=512)),
                ('email_address', models.EmailField(max_length=254)),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='enrollUrl',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='startTime',
        ),
        migrations.AddField(
            model_name='competition',
            name='enroll_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='competition',
            name='enroll_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='competition',
            name='enroll_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='competition',
            name='judging_standard',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='competition',
            name='max_contestants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='num_downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='num_upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competition',
            name='charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competition',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='competition',
            name='procedure',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Competition'),
        ),
        migrations.AddField(
            model_name='judgecompetitionconnection',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Competition'),
        ),
        migrations.AddField(
            model_name='judgecompetitionconnection',
            name='judge_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.OrganizationUser'),
        ),
        migrations.AddField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Competition'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader_contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.ContestantUser'),
        ),
        migrations.AddField(
            model_name='contestantgroupconnection',
            name='contestant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.ContestantUser'),
        ),
        migrations.AddField(
            model_name='contestantgroupconnection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Group'),
        ),
    ]
