# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='img_url',
            field=models.URLField(default=''),
        ),
    ]
