# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_competition_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(related_name='judged_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='joint_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
