# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20181029_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='basic.OrganizationUser'),
            preserve_default=False,
        ),
    ]
