# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_competition_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgecompetitionconnection',
            name='judge_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.ContestantUser'),
        ),
    ]
