# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_group_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstage',
            name='deltaMsg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gstage',
            name='deltaScore',
            field=models.FloatField(default=0.0),
        ),
    ]
