# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_group_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0002_auto_20181129_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='basic.Competition')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviewer_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
